### ISSUE TITLE
Datetime parsing around midnight can go wrong (or at least unexpected)

### ISSUE THREAD

**Issue by maekke97** [holger24/AFD#3]
Hi,
first thanks for a great tool! 

I have an issue occurring sometimes that sends files to the wrong date. 
With a configuration like:

      [files]
          PRECIP*%tY%tm%td*.png

          [destination] my target

              [recipient]
              exec://target/rsync %s user@target:/targetfolder/%tY/%tm/%td/
      [files]
          PRECIP*%T-1d%tY%tm%td*.png

          [destination] my target

              [recipient]
              exec://target/rsync %s user@target:/targetfolder/%T-1d%tY/%tm/%td/

I see some cases, where an input file that arrives shortly before midnight get's distributed to the following day since the actual transfer only happens after midnight.

Is this a known issue and is there a remedy?

**Comment by holger24** [comment]
Hello Markus,

On Tue, 1 Dec 2020, Markus Neumann wrote:

>
> Hi,
> first thanks for a great tool!
>
> I have an issue occurring sometimes that sends files to the wrong date.
> With a configuration like:
>
>   [files]
>       PRECIP*%tY%tm%td*.png
>
>       [destination] my target
>
>           [recipient]
>           exec://target/rsync %s user@target:/targetfolder/%tY/%tm/%td/
>   [files]
>       PRECIP*%T-1d%tY%tm%td*.png
>
>       [destination] my target
>
>           [recipient]
>           exec://target/rsync %s user@target:/targetfolder/%T-1d%tY/%tm/%td/
>
> I see some cases, where an input file that arrives shortly before midnight
> get's distributed to the following day since the actual transfer only
> happens after midnight.
>
> Is this a known issue and is there a remedy?
>
The problem is that two different process handle this. Process amg
handles the [directory] + [files] part and [recipient] is handled by
process fd. And depending how busy the local and/or the remote system
are the time difference becomes bigger.

If you use another scheme, not exec, then you could solve this with
the option trans_srename. With this you can take the date from
the file name. This should then be save.

With exec I would suggest you write a little wrapper script that
parses the date from the file name.

Regards,
Holger

**Comment by maekke97** [comment]
Hi Holger,

thanks for the fast response, that was exactly what I feared... ;)
I will double-check the other schemes and worst case write those wrappers...

Kind regards
Markus
